ALTER TABLE alunos
  MODIFY COLUMN fone VARCHAR(20) NULL DEFAULT NULL,
  MODIFY COLUMN bairro INT NULL DEFAULT NULL,
  MODIFY COLUMN escolaridade INT NULL DEFAULT NULL,
  MODIFY COLUMN estadoCivil INT NULL DEFAULT NULL;

ALTER TABLE professores
  MODIFY COLUMN bairro INT NULL DEFAULT NULL;
